### ISSUE TITLE
Probable typo 

### ISSUE THREAD

**Issue by iamraghavs** [tarr11/tarr11.github.com#1]
In http://douglastarr.com/using-powershell-3-invoke-restmethod-with-basic-authentication-and-json
the line $secpasswd = ConvertTo-SecureString $user -AsPlainText -Force
should probably be
$secpasswd = ConvertTo-SecureString $**password** -AsPlainText -Force

and in the next line
$cred = New-Object System.Management.Automation.PSCredential ($pass, $secpasswd)
should be
$cred = New-Object System.Management.Automation.PSCredential ($user, $secpasswd)

I wasnt able to find the file in order to raise a pull request

**Comment by tarr11** [comment]
Fixed.  Thanks!
